version: "3"

services:
  pg:
  container_name: postgres
  image: postgres:12
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
  ports:
    - "6432:5432"
  volumes:
    - "./data/:/var/lib/postgresql/data"
  pgadmin:
    container_name: pgadmin
    image: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "6000:80"
    depends_on:
      - postgres
